import { lazy, Suspense, useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../auth/AuthContext';
import { useResource } from '../api/useResource';
import { dashboardPermissions, money } from '../api/operations';
import { params, periodStart, units } from '../api/operations';
import type { Analytics, SeriesPoint } from '../api/operations';
import { today, date, number } from '../api/livestock';
import type { CatalogItem } from '../api/livestock';
import { PeriodFilter } from '../components/PeriodFilter';
import { CarePagination } from '../components/CareForm';
import { Button } from '../components/ui/Controls';
const Charts = lazy(() => import('../components/AnalyticsCharts'));
function SeriesTable({ title, rows, unit }: { title: string; rows: SeriesPoint[]; unit: string }) {
  return <article className="panel"><h2>{title}</h2>{rows.length ? <div className="table-scroll"><table><thead><tr><th>Grupo</th><th>Valor ({unit})</th><th>Registros</th></tr></thead><tbody>{rows.map(r => <tr key={r.label}><td>{r.label}</td><td>{number(r.value)}</td><td>{r.count}</td></tr>)}</tbody></table></div> : <p className="muted">Sin registros comparables en el período.</p>}</article>;
}
export function DashboardPage() {
  const { isAdmin, can } = useAuth(); const allowed = isAdmin && dashboardPermissions.every(can);
  const [period, setPeriod] = useState({ from: periodStart(), to: today(), farmId: '' });
  const data = useResource<Analytics>('/api/analytics/overview?' + params(period), allowed);
  const [stockPage, setStockPage] = useState(1);
  useEffect(() => { if (!allowed) return; const timer = window.setInterval(() => { if (document.visibilityState === 'visible') data.reload(); }, 60000); return () => window.clearInterval(timer); }, [allowed, data.reload]);
  const farms = useResource<CatalogItem[]>('/api/farms', allowed && can('farms.list'));
  if (!allowed) return <p role="alert">El dashboard requiere acceso de administrador y permisos para sus indicadores.</p>;
  const d = data.data;
  const currentStockPage = Math.min(stockPage, Math.max(1, Math.ceil((d?.stock.length || 0) / 20)));
  return <section className="operations-page"><span className="eyebrow">DECISIONES CON DATOS</span><h1>Dashboard</h1><p className="muted">Inventario actual e indicadores de los registros de tu finca.</p><PeriodFilter value={period} farms={farms.data || []} onApply={p => { setPeriod(p); setStockPage(1); data.reload(); }} busy={data.loading} />{data.loading && <div className="panel skeleton" style={{ minHeight: 200 }} aria-label="Cargando indicadores" />}{data.error && <p className="error-banner" role="alert">{data.error}<Button onClick={data.reload}>Reintentar</Button></p>}{d && <><p className="muted">Actualizado: {new Intl.DateTimeFormat('es-VE', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(d.generatedAt))} · Período: {date(d.from)} a {date(d.to)}. La valoración y los límites muestran el saldo actual. Se actualiza cada 60 segundos mientras esta página está visible.</p><div className="metric-grid"><article className="panel"><span>Costo del inventario actual</span><strong>{money(d.cost)}</strong></article><article className="panel"><span>Valor de referencia actual</span><strong>{money(d.referenceValue)}</strong></article><article className="panel"><span>En el mínimo o por debajo</span><strong>{d.critical}</strong><Link to="/inventory">Revisar existencias</Link></article><article className="panel"><span>En el máximo o por encima</span><strong>{d.excess}</strong></article></div><p className="muted">Valores en USD de referencia según el catálogo. El valor de referencia usa el precio unitario; no representa ingresos ni utilidad realizada.</p><Suspense fallback={<p role="status">Preparando gráficos…</p>}><Charts data={d} /></Suspense>
    <article className="panel"><h2>Valoración por categoría</h2><div className="table-scroll"><table><thead><tr><th>Categoría</th><th>Costo (USD)</th><th>Referencia (USD)</th></tr></thead><tbody>{d.categories.map(c => <tr key={c.category}><td>{c.category}</td><td>{money(c.cost)}</td><td>{money(c.referenceValue)}</td></tr>)}</tbody></table></div></article>
    <article className="panel"><h2>Límites y rotación del inventario</h2><p className="muted">Rotación = salidas del período / promedio del saldo inicial y final. Solo se calcula con un saldo inicial trazable anterior al inicio del período. El día de apertura puede estar incompleto.</p><div className="table-scroll"><table><thead><tr><th>Insumo / finca</th><th>Saldo actual</th><th>Mín. / Máx.</th><th>Salidas registradas en el período</th><th>Rotación</th></tr></thead><tbody>{d.stock.slice((currentStockPage - 1) * 20, currentStockPage * 20).map(s => <tr key={s.id}><td>{s.product}<small className="muted">{s.farm}</small></td><td><span className={s.stock <= s.min ? 'stock-low tag' : s.stock >= s.max ? 'stock-high tag' : ''}>{number(s.stock, 4)} {units[s.unit]}</span></td><td>{number(s.min)} / {number(s.max)}</td><td>{number(s.outflow, 4)} {units[s.unit]}</td><td>{s.rotation === null ? 'Historial insuficiente' : number(s.rotation, 4) + ' veces'}{s.historySince && <small className="muted">Desde {date(s.historySince)}</small>}</td></tr>)}</tbody></table></div>{!d.stock.length && <p className="muted">No hay existencias registradas.</p>}<CarePagination page={currentStockPage} total={d.stock.length} pageSize={20} onPage={setStockPage} /></article>
    <div className="operations-grid"><SeriesTable title="Leche por día" rows={d.milkByDay} unit="L" /><SeriesTable title="Leche de animales por lote actual" rows={d.milkByCurrentLot} unit="L" /><SeriesTable title="Peso bovino medio por edad al pesaje" rows={d.weightByAge} unit="kg" /></div><p className="muted">Los lotes corresponden a la ubicación actual de los animales y no a una asignación histórica del ordeño. Solo se suma leche en litros ({d.excludedMilk} registros excluidos por unidad). El peso usa el último pesaje de cada bovino en el período y su edad ese día ({d.excludedWeights} bovinos excluidos por fecha de nacimiento desconocida o inválida).</p>
    <article className="panel"><h2>Registros reproductivos del período</h2><div className="metric-grid"><div><span>Diagnósticos positivos</span><strong>{d.positiveChecks}</strong></div><div><span>Diagnósticos negativos</span><strong>{d.negativeChecks}</strong></div><div><span>Positivos / diagnósticos concluyentes</span><strong>{d.positiveCheckPercent === null ? 'Sin diagnósticos concluyentes' : number(d.positiveCheckPercent) + '%'}</strong></div><div><span>Partos registrados</span><strong>{d.calvings}</strong></div></div><p className="muted">Denominador: {d.positiveChecks + d.negativeChecks} diagnósticos positivos o negativos. {d.uncertainChecks} inciertos excluidos. Es una proporción de diagnósticos, no una tasa de concepción por monta. Crías vivas: {d.liveBirths}; mortinatos: {d.stillbirths}.</p></article></>}</section>;
}
