import { test, expect } from '@playwright/test';
import { randomUUID } from 'node:crypto';

test('administrator creates, resets and deactivates an operator with immediate session revocation', async ({ page, request }) => {
  const username = 'p4-user-' + randomUUID().slice(0, 8);
  const password = 'Initial123!User', replacement = 'Changed123!User';
  const auth = await request.post('/api/auth/login', { data: { username: process.env.E2E_ADMIN_USERNAME, password: process.env.E2E_ADMIN_PASSWORD } });
  expect(auth.status()).toBe(200);
  const headers = { Authorization: 'Bearer ' + (await auth.json()).accessToken };
  const farm = (await (await request.get('/api/farms', { headers })).json()).find((f: { data: { code: string } }) => f.data.code === 'DEMO');
  await page.goto('/users');
  await page.getByLabel('Usuario o correo').fill(process.env.E2E_ADMIN_USERNAME!);
  await page.getByLabel('Contraseña', { exact: true }).fill(process.env.E2E_ADMIN_PASSWORD!);
  await page.getByRole('button', { name: 'Entrar a mi finca' }).click();
  await expect(page.getByRole('heading', { name: 'Usuarios', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Crear cuenta', exact: true }).click();
  const panel = page.getByRole('dialog');
  await panel.getByLabel('Nombre completo *', { exact: true }).fill('Phase 4 operator');
  await panel.getByLabel('Usuario *', { exact: true }).fill(username);
  await panel.getByLabel('Correo electrónico *', { exact: true }).fill(username + '@example.test');
  await panel.getByLabel('Rol *', { exact: true }).selectOption('Employee');
  await panel.getByLabel(farm.data.name, { exact: true }).check();
  await panel.getByLabel('Contraseña inicial *', { exact: true }).fill(password);
  await panel.getByRole('button', { name: 'Crear cuenta', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Cuenta creada.' })).toBeVisible();
  await page.getByLabel('Buscar usuario', { exact: true }).fill(username);
  await page.getByRole('button', { name: 'Buscar', exact: true }).click();
  const result = await request.get('/api/admin/users?search=' + username, { headers });
  const user = (await result.json()).items[0];
  expect(user.farmIds).toEqual([farm.id]);
  const login = await request.post('/api/auth/login', { data: { username, password } });
  expect(login.status()).toBe(200);
  const original = await login.json();
  expect((await request.get('/api/admin/users', { headers: { Authorization: 'Bearer ' + original.accessToken } })).status()).toBe(403);
  await page.getByRole('button', { name: 'Restablecer contraseña de ' + username, exact: true }).click();
  await page.getByLabel('Nueva contraseña *', { exact: true }).fill(replacement);
  await page.getByRole('button', { name: 'Restablecer contraseña', exact: true }).click();
  await page.getByRole('dialog', { name: 'Confirmar acción' }).getByRole('button', { name: 'Restablecer contraseña', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Contraseña restablecida;' })).toBeVisible();
  expect((await request.get('/api/animals', { headers: { Authorization: 'Bearer ' + original.accessToken } })).status()).toBe(401);
  expect((await request.post('/api/auth/login', { data: { username, password } })).status()).toBe(401);
  const newLogin = await request.post('/api/auth/login', { data: { username, password: replacement } });
  expect(newLogin.status()).toBe(200);
  const operator = await newLogin.json();
  await page.getByRole('button', { name: 'Editar cuenta de ' + username, exact: true }).click();
  await page.getByLabel('Cuenta activa', { exact: true }).uncheck();
  await page.getByRole('button', { name: 'Guardar cuenta', exact: true }).click();
  await expect(page.getByRole('status').filter({ hasText: 'Cuenta actualizada;' })).toBeVisible();
  await expect(page.getByRole('table', { name: 'Cuentas de usuario' })).toContainText('Inactiva');
  expect((await request.get('/api/animals', { headers: { Authorization: 'Bearer ' + operator.accessToken } })).status()).toBe(401);
  expect((await request.post('/api/auth/refresh', { data: { refreshToken: operator.refreshToken } })).status()).toBe(401);
  expect((await request.post('/api/auth/login', { data: { username, password: replacement } })).status()).toBe(401);
  expect(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)).toBe(false);
});
