import { useState } from 'react';
import { BarChart, Bar, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend } from 'recharts';
import type { Analytics } from '../api/operations';
import { Select } from './ui/Controls';
import { Field } from './Field';
export default function AnalyticsCharts({ data }: { data: Analytics }) {
  const [view, setView] = useState('valuation');
  const rows: Record<string, string | number>[] = view === 'valuation' ? data.categories : view === 'milk' ? data.milkByDay : view === 'lot' ? data.milkByCurrentLot : data.weightByAge;
  return <div className="panel analytics-chart"><Field label="Gráfico"><Select value={view} onChange={e => setView(e.target.value)}><option value="valuation">Valoración por categoría (USD)</option><option value="milk">Leche por día (L)</option><option value="lot">Leche de animales por lote actual (L)</option><option value="weight">Peso medio por edad al pesaje (kg)</option></Select></Field>{!rows.length ? <p className="muted">No hay datos comparables para este gráfico.</p> : <div className="chart-container" style={{ height: 320 }} aria-label="Gráfico de los indicadores seleccionados"><ResponsiveContainer width="100%" height="100%">{view === 'milk' ? <LineChart data={data.milkByDay}><CartesianGrid strokeDasharray="3 3" stroke="var(--line)" /><XAxis dataKey="label" stroke="var(--muted)" /><YAxis stroke="var(--muted)" /><Tooltip /><Line type="monotone" dataKey="value" name="Leche (L)" stroke="var(--primary)" strokeWidth={3} /></LineChart> : <BarChart data={rows}><CartesianGrid strokeDasharray="3 3" stroke="var(--line)" /><XAxis dataKey={view === 'valuation' ? 'category' : 'label'} stroke="var(--muted)" /><YAxis stroke="var(--muted)" /><Tooltip /><Legend />{view === 'valuation' ? <><Bar dataKey="cost" name="Costo (USD)" fill="var(--primary)" radius={[4, 4, 0, 0]} /><Bar dataKey="referenceValue" name="Referencia (USD)" fill="var(--info)" radius={[4, 4, 0, 0]} /></> : <Bar dataKey="value" name={view === 'weight' ? 'Peso medio (kg)' : 'Leche (L)'} fill="var(--primary)" radius={[4, 4, 0, 0]} />}</BarChart>}</ResponsiveContainer></div>}<p className="muted">Los valores también están disponibles en las tablas del dashboard.</p></div>;
}
